OPICoach/OPICoach

frontend/src/components/LoginInput.jsx

feat(fe): add logininput component

---

frontend/src/App.jsx
frontend/src/components/SideBar.jsx

learn, test, information 페이지 추가

feat(fe): add new page

---

frontend/src/components/homePage/HomeExistUser.jsx
frontend/src/components/homePage/HomeNewUser.jsx
frontend/src/components/homePage/OnboardingSurvey.jsx
frontend/src/pages/Home.jsx

홈페이지의 sidebar size 일관성을 위해 HomeExistUser, HomeNewUser 컴포넌트 css을 변경하였습니다.

fix(fe): fix home page weight

---

frontend/src/assets/back_button.svg
frontend/src/components/BackButton.jsx
frontend/src/components/SideBar.jsx
frontend/src/components/chatPage/MessageInput.jsx
frontend/src/components/chatPage/MessageList.jsx
frontend/src/hooks/useResizeHeight.jsx
frontend/src/hooks/useResizeWidth.jsx
frontend/src/pages/Fillers.jsx
frontend/src/pages/Home.jsx
frontend/src/pages/Information.jsx
frontend/src/pages/Learn.jsx
frontend/src/pages/StudyMaterials.jsx
frontend/src/pages/Test.jsx
frontend/src/pages/TestStart.jsx

1. information page 추가
2. filler page 추가
3. back button 추가
4. study materials에서 채팅창 사이즈 조절 가능 -> hook 생성
5. 채팅 페이지를 MessageList, MessageInput으로 리팩토링
6. sidebar 열고 닫기 기능

feat(fe): add infor, filler, backbutton, resize hook, refatoring

---

frontend/src/components/SideBar.jsx

fix(fe): fix error sidebar

---

frontend/src/App.jsx
frontend/src/components/homePage/EditUserInfoButton.jsx
frontend/src/components/homePage/HomeExistUser.jsx
frontend/src/pages/Edit.jsx

feat(fe): add edit page

---

frontend/src/components/SideBar.jsx

fix(fe): fix sidebar toggle icon

---

frontend/src/api/atom.js
frontend/src/components/SideBar.jsx
frontend/src/components/chatPage/AIMessage.jsx
frontend/src/components/chatPage/MessageButton.jsx
frontend/src/components/chatPage/MessageList.jsx
frontend/src/components/chatPage/UserMessage.jsx
frontend/src/components/homePage/HomeExistUser.jsx
frontend/src/pages/Fillers.jsx
frontend/src/pages/Information.jsx
frontend/src/pages/StudyMaterials.jsx

1. chatPage 리팩토링
2. sidebar height style 바꿈
3. homepage padding 조정

fix(fe): refactoring and fix sidebar and homePage

---

frontend/src/components/LoginSignUpInput.jsx
frontend/src/pages/Login.jsx
frontend/src/pages/SignUp.jsx
frontend/src/styles/global.css

1. login/signup page에서 버튼 누르면 JSON형식으로 파싱하여 console에 출력
- 유저 DB 미완성으로 api 아직 없음

test(fe): parse user input to JSON format

---

frontend/src/pages/StudyMaterials.jsx

1. Learning Page에서 유저가 질문한 것에 대한 답변을 LLM으로 부터 받아서 출력 구현

feat(fe): learning page 유저 질문 및 답변 구현

---

frontend/src/pages/TestStart.jsx
frontend/src/recoil/atoms.js

1. timer: start -> stop -> reset으로 변경, start 시 마이크로 녹음 가능
2. continue -> play로 변경: play 시 마이크 녹음본이 자동으로 재생되게 구현
-> 추후 수정 필요한 임시 구현 단계임

feat(fe): test timer and voice features added

---

frontend/src/pages/Login.jsx
frontend/src/pages/SignUp.jsx
frontend/src/recoil/atoms.js
frontend/src/recoil/authAtoms.js

1. useState에서 useRecoilState로 변경

feat(fe): change to Recoil State

---

frontend/src/pages/SignUp.jsx

1. signup 페이지에서 서버로 user data json 형식으로 전송 가능하게 변경

feat(fe, be): sign up communicate with DB

---

frontend/src/pages/Test.jsx

fix(fe): fix test page

---

frontend/src/components/homePage/HomeNewUser.jsx
frontend/src/pages/Edit.jsx
frontend/src/pages/Fillers.jsx
frontend/src/pages/Home.jsx
frontend/src/pages/Information.jsx

1. page들마다 상단에 title 추가
2. edit page 기능 수정 (major, background까지 표시될 수 있도록)

fix(fe): test page

---

frontend/src/api/api.js
frontend/src/components/LoginSignUpInput.jsx
frontend/src/pages/Login.jsx

1. 로그인 기능 api 생성
2. 로그인 기능 동작 완료

feat(fe): add login api 

---

frontend/src/api/api.js
frontend/src/api/atom.js
frontend/src/components/SideBar.jsx
frontend/src/components/sideBar/SideBar.jsx
frontend/src/components/sideBar/SideBarLearnSection.jsx
frontend/src/pages/Edit.jsx
frontend/src/pages/Home.jsx
frontend/src/pages/Information.jsx
frontend/src/pages/Learn.jsx
frontend/src/pages/Test.jsx
frontend/src/pages/TestStart.jsx

1. session api 연결
2. session 목록 구현

feat(fe): session 관련 기능

---

frontend/package-lock.json
frontend/package.json
frontend/src/api/api.js
frontend/src/components/chatPage/MenuSettingsButton.jsx
frontend/src/components/chatPage/MessageInput.jsx

1. 추가기능을 위한 버튼 생성
2. note , 모델 변경 항목 추가

feat(fe): 추가 기능 버튼

---

frontend/src/api/api.js
frontend/src/atom/learnAtom.js
frontend/src/components/chatPage/MessageList.jsx
frontend/src/components/sideBar/SideBar.jsx
frontend/src/components/sideBar/SideBarLearnSection.jsx
frontend/src/pages/Learn.jsx
frontend/src/pages/Note.jsx
node_modules/.package-lock.json
package-lock.json
package.json

fix(fe):api

---

frontend/src/api/api.js
frontend/src/atom/noteAtom.js
frontend/src/components/sideBar/SideBar.jsx
frontend/src/components/sideBar/SideBarLearnSection.jsx
frontend/src/pages/Learn.jsx
frontend/src/pages/Note.jsx
frontend/src/pages/Test.jsx
frontend/src/pages/TestStart.jsx

1. learning title 생성 부분 수정
2. noteAtoms 생성

fix(fe): learning page & add noteAtoms

---

frontend/src/atom/learnAtom.js
frontend/src/components/sideBar/SideBar.jsx
frontend/src/components/sideBar/SideBarLearnSection.jsx
frontend/src/pages/Learn.jsx

fix(fe): ai loading

---

frontend/src/components/sideBar/SideBar.jsx
frontend/src/components/sideBar/SideBarLearnSection.jsx

1. 처음 세션을 생성할 때 세션 이름 변경
2. ai 로딩중일 때 모든 사이드바 탭 클릭 X

fix(fe): fix new session name

---

frontend/src/components/chatPage/AIMessage.jsx
frontend/src/components/notePage/NoteDetail.jsx

fix(fe): fix markdown error

---

frontend/src/components/chatPage/AIMessage.jsx
frontend/src/components/notePage/NoteDetail.jsx

style(fe): modify font color(markdown)

---

frontend/src/App.jsx
frontend/src/api/api.js
frontend/src/assets/sidebar/vocab.svg
frontend/src/components/sideBar/SideBar.jsx
frontend/src/pages/VocabPage.jsx

feat(fe): restore vocab/idiom

---

frontend/src/components/homePage/HomeNewUser.jsx
frontend/src/components/homePage/OnboardingSurvey.jsx
frontend/src/components/sideBar/SideBar.jsx
frontend/src/pages/Home.jsx
frontend/src/pages/SignUp.jsx
frontend/src/pages/TestHistory.jsx

1. sidebar error 문제 해결
2. history default type 지움

fix(fe): fix sidebar error

---

frontend/src/pages/TestStart.jsx

1. test buttons: 비활성화 및 Stop 기능
2. test 시간 90초로 setting 및 timer 정확하게 표시

feat(fe): change test buttons
